/**
 * @file kernel/fs/ramdisk.hpp
 * @brief Ramdisk driver for parsing embedded ustar initrd archives
 *
 * Provides a Ramdisk class that parses a ustar-format initial ramdisk
 * embedded in the kernel binary.  The archive is accessed via linker
 * symbols (_binary_initrd_start / _binary_initrd_end) generated by
 * CMake from an external .tar file.
 *
 * Usage:
 *   cinux::fs::Ramdisk rd;
 *   rd.mount();
 *   // File names and sizes are printed to serial during mount
 *
 * Namespace: cinux::fs
 */

#pragma once

#include <stdint.h>
#include <stddef.h>

namespace cinux::fs {

// ============================================================
// Ramdisk Entry Info
// ============================================================

/// Maximum displayable file name length (for safe printing)
static constexpr uint32_t RAMDISK_NAME_MAX = 100;

/**
 * @brief Describes a single file entry found in the ramdisk
 */
struct RamdiskEntry {
    const char* name;     ///< Pointer into the ustar header name field
    uint64_t    size;     ///< File size in bytes (parsed from octal)
    const void* data;     ///< Pointer to the file data within the archive
};

// ============================================================
// Ramdisk Class
// ============================================================

/**
 * @brief Parses and provides access to a ustar-format initial ramdisk
 *
 * On mount(), iterates through all ustar entries in the embedded
 * archive, validates each header's magic field, and prints file
 * names and sizes to the serial console.
 *
 * The ramdisk is embedded at link time via CMake's add_custom_command
 * which converts a .tar file into a linkable object with symbols
 * _binary_initrd_start and _binary_initrd_end.
 */
class Ramdisk {
public:
    /**
     * @brief Mount and parse the embedded initrd archive
     *
     * Reads the ustar archive bounded by the linker symbols
     * _binary_initrd_start and _binary_initrd_end.  For each valid
     * entry (magic == "ustar"), prints the file name and size to
     * the serial console via kprintf.
     *
     * Entries with typeflag '0' are regular files; typeflag '5'
     * are directories.  The data blocks for files are skipped
     * according to their size (rounded up to 512-byte blocks).
     *
     * @return Number of valid entries found, or 0 if the archive
     *         is empty or the magic is invalid
     */
    uint32_t mount();

    /**
     * @brief Get the base address of the ramdisk archive
     * @return Pointer to the start of the archive, or nullptr if not mounted
     */
    const void* base() const;

    /**
     * @brief Get the total size of the ramdisk archive in bytes
     * @return Size in bytes, or 0 if not mounted
     */
    uint64_t total_size() const;

private:
    /// Pointer to the start of the embedded archive
    const uint8_t* base_{};

    /// Total size of the archive in bytes
    uint64_t size_{};
};

}  // namespace cinux::fs
